apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bootapp-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: pksdemo-mysql-deployment
  labels: 
    app: pksdemo-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pksdemo-mysql
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: pksdemo-mysql
    spec:
      containers:
      - name: pksdemo-mysql
        image: tkaburagi/pksdemo-mysql:1.4
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: bootapp-persistent-storage
          mountPath: /app/data
      volumes:
      - name: bootapp-persistent-storage
        persistentVolumeClaim:
          claimName: bootapp-pv-claim

